# Generated by Django 3.0.8 on 2020-08-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.TextField(default='https://www.dropbox.com/s/tg3itjuxuwebaw3/Then-and-Now_-no-image-found.jpg?dl=0'),
        ),
    ]
