# Generated by Django 3.0.8 on 2020-08-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200807_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.TextField(default='https://www.teknozeka.com/wp-content/uploads/2020/03/wp-header-logo-33.png'),
        ),
    ]
