# Generated by Django 3.1.2 on 2020-12-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201211_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('1', 'Electronic'), ('2', 'Non electronic'), ('3', 'Other categories')], default=30, max_length=64),
        ),
    ]
